### ISSUE TITLE
StackBlitz link can't be found.

### ISSUE THREAD

**Issue by tibuurcio** [julianobrasil/multipicker#7]
Hi Juliano, thank you for putting time into customizing Angular's datepicker.

The link at StackBlitz is showing a not found message.

I used to consult your StackBlitz link in order to get implementation details. I know we can get it from here but the StackBlitz is a nice to have. Also, the link is somewhere in the angular material issues which is where I found it in the first place.

EDIT: Found it: [#4853](https://github.com/angular/material2/issues/4853)

**Comment by julianobrasil** [comment]
Sorry about that! I fixed the link!
